name: ci

on:
  pull_request:
  push:
    branches:
     - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Updating packages database
        run: sudo apt-get -qq update
      - name: Install CLI Dependencies
        run: sudo apt-get install -y ldap-utils oathtool go-bindata
      - name: LS
        run: ls -la
      - name: PWD
        run: pwd
      - name: Make Bindata
        run: make bindata
      - name: Fetch Go dependencies
        run: go get -t -v ./...
      - name: Fail if a .go file hasn't been formatted with 'go fmt'
        run: diff -u <(echo -n) <(gofmt -d ./)
      - name: Full compile test
        run: make all
      - name: Output hashes to the build log
        run: cat bin/*.sha256
      - name: Integration test with compiled binary
        run: make test
